import { Nerko_One } from "next/font/google";
import "./globals.css";
import Navbar from "./_component/Navbar/page";

const nerko_One = Nerko_One({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "Game",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/Image/logo-sm.png" type="image/png" />
      </head>
      <body className={`${nerko_One.className} antialiased bg-[#272b30]`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
